---
- hosts: localhost
  connection: local
  vars_files:
      - vars/common.yml

  tasks:
      - ansible.builtin.import_tasks: tasks/node.yml
      - ansible.builtin.import_tasks: tasks/core.yml
  pre_tasks:
      - name: Get my user
        ansible.builtin.set_fact:
            current_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
