---
- name: Install Core Packages

  vars:
      brew_exe_path: "{% if ansible_facts['architecture'] == 'arm64' %}/opt/homebrew/bin{% else %}/usr/local/bin{% endif %}"

      homebrew_packages:
          - { name: helix }
          - { name: bash }
          - { name: nvm }
          - { name: zellij }
          - { name: zsh }
          - { name: zsh-autosuggestions }
          - { name: powerlevel10k }
          - { name: alacritty, cask: true }
          - { name: anaconda, cask: true }
          - { name: cocoapods, cask: true }
          - { name: android-studio, cask: true }
          - { name: google-chrome, cask: true }
          - { name: visual-studio-code, cask: true }
          - { name: slack, cask: true }
          - { name: spotify, cask: true }
          - { name: postman, cask: true }

      homebrew_fonts:
          - { name: font-fontawesome }
          - { name: font-freefont }
          - { name: font-meslo-lg-nerd-font }
          - { name: font-hack-nerd-font }
          - { name: font-jetbrains-mono }

  block:
      - name: Update Homebrew
        community.general.homebrew:
            path: '{{ brew_exe_path }}'
            update_homebrew: yes

      - name: Install homebrew packages as casks
        community.general.homebrew_cask:
            path: '{{ brew_exe_path }}'
            name: '{{ item.name }}'
            state: "{{ item.state | default('installed') }}"
        loop: "{{ homebrew_packages | selectattr('cask', 'defined') | selectattr('cask', 'equalto', true) | list }}"

      - name: Install homebrew packages as formulas
        community.general.homebrew:
            path: '{{ brew_exe_path }}'
            name: '{{ item.name }}'
            state: "{{ item.state | default('present') }}"
        loop: "{{ homebrew_packages | rejectattr('cask', 'defined') | list }}"

      - name: Install Fonts
        community.general.homebrew_cask:
            path: '{{ brew_exe_path }}'
            name: '{{ item.name }}'
            state: "{{ item.state | default('installed') }}"
        with_items: '{{ homebrew_fonts }}'

      - name: Update PowerLevel10K themes
        ansible.builtin.git:
          repo: https://github.com/alacritty/alacritty-theme
          dest: "~/.config/alacritty/themes"
          force: yes

      - name: Change shell to zsh
        ansible.builtin.user:
            name: '{{ current_user }}'
            shell: /bin/zsh

      - name: Load ~/.zshrc and ~/.zprofile
        shell: |
          source ~/.zshrc && source ~/.zprofile
        args:
          executable: /bin/zsh
