---
- name: Install Node
  become: yes
  become_user: root
  block:
      - name: Install nvm
        ansible.builtin.shell: >
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.7/install.sh | bash
        args:
            executable: /bin/bash
            chdir: "{{ lookup('env', 'HOME')}}"
            creates: "{{ lookup('env', 'HOME')}}/.nvm/nvm.sh"

      - name: Setup .profile
        ansible.builtin.lineinfile:
            path: "{{ lookup('env', 'HOME')}}/.profile"
            line: "source {{ lookup('env', 'HOME')}}/.nvm/nvm.sh" # This will make sure Node is on the user's PATH
            create: yes

      - name: Install node
        ansible.builtin.shell: |
            "source {{ lookup('env', 'HOME')}}/.nvm/nvm.sh && nvm install {{item}}"
        args:
            executable: /bin/bash
            chdir: "{{ lookup('env', 'HOME')}}"
            creates: "{{ lookup('env', 'HOME')}}/.nvm/versions/node/v{{item}}"
        loop:
            - 16.15.1
            - 18.19.1
            - 20.9.0
